### ISSUE TITLE
Launcher shortcut opens standard browser instead of this browser

### ISSUE THREAD

**Issue by kyoforkshomebrews** [woheller69/browser#10]
I tap on the shortcut and it opens in Firefox instead of FREE Browser.

**Comment by woheller69** [comment]
then you need to change your standard browser app in Android settings

**Comment by Spike-from-NH** [comment]
No, @kyoforkshomebrews needs to find Free Browser icon (swipe up on the home page), long-press the icon, and choose "Add to home page". That's how to create a shortcut. @woheller69's solution would make Free Browser the default for viewing files of suitable types, such as `.HTM`. Also useful, but different.

**Comment by woheller69** [comment]
In the save menu you can also create shortcut links on the home screen for any website if this is what you mean.

**Comment by Spike-from-NH** [comment]
If he meant an existing home-screen shortcut, then both your solutions are better than mine.
