### ISSUE TITLE
Greasemonkey scripts not working

### ISSUE THREAD

**Issue by Kurasami** [woheller69/browser#12]
I've been trying to get scripts working and nothing is happening. I copy-paste the script in from Greasyfork and it simply doesn't work.

If I enable the debug option, I can't see any logs or information anywhere (where is it?) however, the browser becomes extremely slow with this option enabled.

I also checked the instructions here: https://github.com/woheller69/browser/issues/11#issuecomment-1842104480
and according to this, it should work fine.

I'm using Browser version: 1.6 from the F-Droid repo.

**Comment by woheller69** [comment]
If debug is on, you see a toast message, if your script is executed

**Comment by Kurasami** [comment]
Yeah no toast message at all.

**Comment by woheller69** [comment]
Then your @match probably does not match the Url...

**Comment by Kurasami** [comment]
I want it to match every single site I visit. The script doesn't make use of @match at all because it is supposed to run everywhere.

**Comment by woheller69** [comment]
// ==UserScript==
    // @name Test
    // @match https://*.*/
    // @run-at document-end
    // ==/UserScript==
    alert("Test");

This runs everywhere

**Comment by 825i** [comment]
Thanks. It would be great if this was listed on the scripts page of the settings so people knew this was the case.

**Comment by woheller69** [comment]
I have added it already in the updated Readme on my current development branch for the Cookie Banner Blocker

https://github.com/woheller69/browser/tree/cookieBannerBlocker

Will be released soon

**Comment by 825i** [comment]
Awesome!
