### ISSUE TITLE
Fullscreen videos are all bugged out

### ISSUE THREAD

**Issue by SecularSteve** [woheller69/browser#13]
Playing YouTube videos in the browser itself results in a broken full-screen where the video is completely off-centre.

On top of that, the three navigation buttons don't disappear back into the screen as they should if literally any video is full-screen, even the less buggy ones.

Kind of easy to recreate. If you need screenshots, I'll provide them.

**Comment by woheller69** [comment]
You have to switch off fingerprint protection. Otherwise Youtube gets a wrong screen size

**Comment by woheller69** [comment]
But even better: use NewPipe for YouTube...
