### ISSUE TITLE
New Logo Suggestion/Proposal

### ISSUE THREAD

**Issue by SecularSteve** [woheller69/browser#14]
Hello Again...

I've decided to provide you with some creative input again, just like in Lavseeker/Lavatories.

Despite the bug I mentioned earlier, this is an interesting browser to use, especially concerning the emphasis on scripting.
As a frequent user of the FOSS browser likewise, I welcome your more ergonomic approach.
Everything's promising about it except for one thing.

No offence to the original creator, but the current icon is not the least bit appealing.

It makes me think that this is one of those browsers you find on the Play Store that's probably stolen assets by some third-world developer trying to implement a crypto-mining-virus on your device as soon as it even touches it by one piece of data. Probably adware-filled too.

So I've provided my own design that's sure to appeal to, and attract more people:

![FREE_Browser_New_Logo](https://github.com/woheller69/browser/assets/33793273/532c2437-58fc-4b2e-be11-71ca91f81963)
![FREE_Browser_New_Logo](https://github.com/woheller69/browser/assets/33793273/c1313931-a51b-40ad-8c7b-68a44515bcfb)
[FREE_Browser_New_Logo.zip](https://github.com/woheller69/browser/files/13624346/FREE_Browser_New_Logo.zip)

I've based it partially on the Juneteenth flag, America's most recent officially incorporated state-wide holiday, which represents the day all of the slaves in America were finally freed (the final Emancipation Proclamation by decree of the Third General Order in Galveston, Texas on 19th of June, 1865; though Kentucky and Delaware refused to implement the 13th amendement until the 18th of December). The Dove carrying the magnifyer is a reference to the most common representation of peace, freedom and unity, except the dove is not carrying an olive twig. 

As last time, ZIP contains the SVG and PNG.

Made in Inkscape, CC BY-SA 4.0

**Comment by woheller69** [comment]
Thanks, but I like the current logo and will keep it. Your proposal reminds me of Twitter :-)

**Comment by SecularSteve** [comment]
To each their taste I suppose.

If you ever get an itch to at the very least modify the design of the current logo, feel free to mention it. My doors are always open.

**Comment by woheller69** [comment]
closing this for now

**Comment by Spike-from-NH** [comment]
Existing logo is a bit garish for me.

On the proposed logo: Just as bad as a logo that connotes "third world…stolen assets" is a logo dripping with U.S. political correctness, including black separatism. This software has nothing to do with Juneteenth or peace.

Start with a globe for WWW. Add ornaments to suggest "FREE" of corporate browsers and their Marketing Partners—perhaps broken chains.
