### ISSUE TITLE
java.util.regex.PatternSyntaxException: Error in {min,max} interval near index

### ISSUE THREAD

**Issue by 825i** [woheller69/browser#16]
I am getting this error when trying to run a script on a page:

![WhatsApp Image 2023-12-13 at 11 32 56_f639a1d3](https://github.com/woheller69/browser/assets/58630825/d02ca0f1-6e58-44cc-8cb2-4bb1154fc6b1)

I don't get this error on any other browser. In fact the script also works fine on another browser that allows userscripts (Kiwi Browser).

Is there something on Free Browser that prevents my regex script from working?

P.S. According to [this](https://stackoverflow.com/questions/20346705/exception-in-regex-pattern), this guy had some problem with his .json parser. I've run my userscript through dozens of linters and checkers and nothing has ever complained and as I said, other browsers have no problem with this script.

**Comment by woheller69** [comment]
if you switch on Debug, does it show that your script is being executed? Or is this a problem with @match?

**Comment by 825i** [comment]
I have debug switched on, that's what the toast is showing. So it is trying to execute the script but it's hitting that error and not working.

**Comment by woheller69** [comment]
then it does not like your @match pattern...
how does that look like?

**Comment by woheller69** [comment]
[MatchPatterns.PDF](https://github.com/woheller69/browser/files/13659082/MatchPatterns.PDF)
@match should look like specified here. http and https only

**Comment by 825i** [comment]
The match pattern is fine. I think the problem is that @match does not support regex. Only @Include works for that. So sadly I can't use this browser because none of my regex scripts work.

**Comment by woheller69** [comment]
Please try this. No idea if it works.
If a @match pattern starts with "/" and ends with "/" it uses the pattern between as regex and does not convert it into a regex

[app-release.apk.zip](https://github.com/woheller69/browser/files/13852369/app-release.apk.zip)

Backup app data
Uninstall
Remove .zip and install

**Comment by woheller69** [comment]
@825i Have you tried it?

**Comment by woheller69** [comment]
@825i Do your scripts work with this version? Without testing it will not be part of the code...
