### ISSUE TITLE
Support for media session

### ISSUE THREAD

**Issue by medismail** [woheller69/browser#18]
It is will be good if have support for media session: 
https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API

**Comment by woheller69** [comment]
I don't think this works with Android Webview

**Comment by medismail** [comment]
As I understand here https://bugs.chromium.org/p/chromium/issues/detail?id=925997
The app use webview can implement the API

**Comment by woheller69** [comment]
It could if there was an API. But it does not exist

**Comment by woheller69** [comment]
We can reopen if someone else has solved this in webview
