### ISSUE TITLE
"Certificate Authority Not Trusted"

### ISSUE THREAD

**Issue by P650SE** [woheller69/browser#19]
Thanks for your efforts developing this browser.

I have just one question. Is there a way to disable this message from appearing? I think it would be beneficial to have an option in the settings to disable these alerts, if desired.

![Screenshot_20231229-161418_FREE_Browser_cr](https://github.com/woheller69/browser/assets/60034877/a7d8c9f1-9401-4f3b-9fbd-bc76693fae44)

**Comment by woheller69** [comment]
maybe that is an issue with a webserver in your own firewall or adblocker like AdAway. They are using untrusted certificates

**Comment by P650SE** [comment]
Oh, you're right. It seems to be caused by using NextDNS. I disabled my private DNS settings and the messages have since disappeared. Thanks!

I had the same issue in Via Browser. But in Via, there is an option to disable alerts for untrusted certificates.

**Comment by P650SE** [comment]
Entirely my fault! I fixed it by going to NextDNS settings and disabling the option 'Block Page'

Now I can use the browser with NextDNS enabled, and the certificate alerts do not appear.

Apologies!

![Screenshot_20231229-180311_NextDNS_Manager_cr](https://github.com/woheller69/browser/assets/60034877/07006016-60c7-4dff-8331-258a79a2ee91)
