### ISSUE TITLE
Enabling images

### ISSUE THREAD

**Issue by Spike-from-NH** [woheller69/browser#2]
Thank you for this app!
① The Readme states a rule that, although the user can disable downloading of images as a global setting, they will be downloaded anyway if operating over WiFi. However, this is not the same thing as "someone else is paying." My only 2 tablets running A10+ (as you require) are on WiFi to my hotspot, which is billed per megabyte. Please cancel this rule or go 3-state as the old Firefox "Data Saver" did: Always/WiFi/Blocked.
② It would be nice if images were enabled per website. On some websites, images are the information you are seeking; on others, they are merely decoration or advertising.

**Comment by woheller69** [comment]
I will maybe add a switch in settings like
`Define as Metered Connection   on/off`
Usually this would be off. Mobile data would always be considered as "Metered", WIFI usually as not "Metered"
With the switch on all connections would be considered as "Metered" and images would be loaded only if the
button for images is switched on.

**Comment by Spike-from-NH** [comment]
This may be smarter than the old Firefox Data Saver. If images were the only issue, the tri-state mode I propose would be best. However, informing Free Browser of the nature of the connection may permit future adaptations.

**Comment by woheller69** [comment]
You can try this version. I has lots of improvements and also a switch for metered connection in settings

Backup App data
Uninstall
Remove .zip and install
Restore App data
[app-release.apk.zip](https://github.com/woheller69/browser/files/13453672/app-release.apk.zip)

**Comment by Spike-from-NH** [comment]
Thanks, I have installed this. I have enabled metered connection and disabled images but still get images from forecast.weather.gov/MapClick.php?lat=43&lon=-71&FcstType=text&TextType=2

**Comment by woheller69** [comment]
then these images are loaded via a different mechanism and cannot be blocked with the built-in rule in webview.
But they are tiny :-)

**Comment by Spike-from-NH** [comment]
Yes, this is not a costly problem; only my first test of your new release, which did not go as planned.

I understand there are ways (such as JavaScript) to load images that you can't catch. I sometimes read the news with Data Saver and one British newspaper insists I view high-def photos anyway. But Data Saver does block the images in that weather report.

**Comment by Spike-from-NH** [comment]
Apologies; it's now inhibiting the weather thumbnail images as intended, also photos from a local newspaper website. Needed to restart the app.
