### ISSUE TITLE
Desktop mode

### ISSUE THREAD

**Issue by medismail** [woheller69/browser#20]
Can you add an option to enable desktop mode to view a web pages like on desktop.
https://stackoverflow.com/questions/14688030/setting-webview-to-view-desktop-site-and-not-mobile-site

**Comment by woheller69** [comment]
It is there...

**Comment by medismail** [comment]
> It is there...

You mean change user agent?

**Comment by woheller69** [comment]
The icon with the monitor

**Comment by medismail** [comment]
Sorry I miss that
