### ISSUE TITLE
Running in background all the time

### ISSUE THREAD

**Issue by R7010A** [woheller69/browser#23]
Leaving the browser should stop it running in background.
ATM it is shown in Recent Apps, even I leave it with the 3-Dot-menu.

**Comment by woheller69** [comment]
ATM?

**Comment by R7010A** [comment]
At the moment
Sorry für mein schlechtes Englisch 🙏

**Comment by woheller69** [comment]
das ist bei allen apps so, sie sind dann pausiert.

**Comment by R7010A** [comment]
Und benötigen laufend Akku.
Du hast dich mit FREE Browser in weiten Teilen an den FOSS angelehnt, was ich super finde mit dem Unterschied, dass du viele Dinge **user-freundlicher** umgebaut hast (untere Leiste mit mehr buttons für den direkten Zugriff etc). Top.!!!
Der FOSS wird beim Verlassen komplett beendet. Vlt. ein feature, das du aufnehmen könntest.
Danke.

**Comment by woheller69** [comment]
FOSS taucht bei mir auch in recent apps auf. und Akku wird auch nicht benötigt

**Comment by R7010A** [comment]
Seltsam. 
Egal. Ich finde deinen FREE genial.

Wenn ich dich gerade an der Strippe habe:
Bei deiner RadarWeather App bekomme ich keine Verbindung zu OWM, trotz Registrierung. Irgend etwas mit dieser One call API 3.0 passt da nicht.
Benötige ich mehr als die Registrierung bei OWM?
VG

**Comment by woheller69** [comment]
owm  geht nur für alte lizenzen.

omWeather nutzen.

**Comment by R7010A** [comment]
Closed, all fine. Thx
