### ISSUE TITLE
Custom filter list

### ISSUE THREAD

**Issue by Saibot1945** [woheller69/browser#25]
Can you add support for custom filter list?
I want to add legitimate url shortener and stevenblack annoyance list

**Comment by woheller69** [comment]
Please try.

-Backup app data
-Uninstall
-Remove .zip and install
-Restore app data

In Custom Host List you can add your domains, use a new line for each domain
[app-release.apk.zip](https://github.com/woheller69/browser/files/14007883/app-release.apk.zip)

**Comment by Saibot1945** [comment]
Tried that, I'm using https://filterlists.com/
to find domain links, added hosts like the ss. 
Will it work correctly?
Thanks for adding my requested feature. Didn't expect you will add this feature this fast!

![Screenshot_20240122-170850](https://github.com/woheller69/browser/assets/88901460/b6404f4b-3ced-4fbe-8df0-2ed7414e9070)

**Comment by woheller69** [comment]
It will not download lists.
You can just paste a list of domains to block:

test.com
test2.org
test3.uk

etc

**Comment by woheller69** [comment]
otherwise I would recommend to install AdAway and add your lists there

**Comment by Saibot1945** [comment]
Is it possible to add cu
