### ISSUE TITLE
URL Tab

### ISSUE THREAD

**Issue by AlexanderQueen** [woheller69/browser#26]
Is it possible to set URL Tab to stay at top? If no, can you add function in next update to choose which side to be? Thx, a lot. Project is amazing.

![git url](https://github.com/woheller69/browser/assets/55955916/db247958-1c15-4281-a8ef-cf3af5b2c95e)

**Comment by woheller69** [comment]
This is not possible, unfortunately. The project is based on bottom navigation. Would break too many things

**Comment by AlexanderQueen** [comment]
So sad to hear that. I tested browser for a while, its smooth,fast,reliable. A good one for an old phone. 
Tested on: Redmi Note 3 pro(Kenzo), A10 no gApps.

**Comment by woheller69** [comment]
Once you get used to bottom navigation you will never want to return to top navigation...
