### ISSUE TITLE
Update adblock lists

### ISSUE THREAD

**Issue by R7010A** [woheller69/browser#27]
Hi Wolfgang,
I checked the date of the adblock lists today, last update time was January 21st.
Are the lists automatically updated by FREE and if so, at what intervals? If not, how can I update it manually?

**Comment by woheller69** [comment]
They are automatically updated every 3 days on WIFI, once a week otherwise
You will see a Toast message "Adblock" when downloading

**Comment by R7010A** [comment]
Ah ok, now I also understand the occasional toast messages (AdBlock and Cookie Banner) at the start of FREE. Thanks for the info.
Great browser, love it every day more and more.
