### ISSUE TITLE
Button state could be clearer

### ISSUE THREAD

**Issue by Spike-from-NH** [woheller69/browser#3]
The app's buttons that disclose enabled/disabled status are ambiguous. One mode is colorful (light green) but has an icon that is subdued. The other mode is gray but the icon is clear. Which denotes "disabled"?

**Comment by woheller69** [comment]
switches are enabled when they are green

**Comment by Spike-from-NH** [comment]
Thanks for that; do you see the need to rework this style to make this clearer?

**Comment by woheller69** [comment]
I think it is quite clear...

**Comment by Spike-from-NH** [comment]
Perhaps make icons more opaque in green and less opaque in gray?

**Comment by woheller69** [comment]
Colors will stay as they are for now
