### ISSUE TITLE
New bookmark from the bookmarks list

### ISSUE THREAD

**Issue by Cwpute** [woheller69/browser#30]
When i open the bookmarks list, it's either to search for a bookmark, i know i have, or see if i have already bookmarked something similar to the page i'm browsing. Often times, the next step is to bookmark the curent page i'm viewing, but for that i need to quit the bookmark list, open the three-dots menu, open the floppy-disc tab and select "save as new bookmark"… which i find a bit umintuitive.

Wouldn't it be more logical to be able to add a bookmark from the bookmarks list ?
Please make it a feature.

**Comment by woheller69** [comment]
For a new bookmark just long click the bookmark symbol

**Comment by Cwpute** [comment]
Oh right, you tell about this on the about page for this project.
Perhaps you should include a little guide or tutorial in your app, or even just the picture you created, for people to get reference for what they can do in the browser once they've downloaded it (since not every user will see this repository page).

**Comment by woheller69** [comment]
also there. The page is opened at first start and is available via 3dots  (i) symbol

**Comment by Cwpute** [comment]
I was confused ! i thought it had just openned the github repo page. I did click on that button but it took me to Github, so i thought it was just a like to the repo, nor for actual information about how the browser works…

I should have waited some time before the page fully loaded probably, but this is still a bit confusing i'd argue: a more formal presentation would be welcome.
