### ISSUE TITLE
Light mode how to make visible?

### ISSUE THREAD

**Issue by LISvar** [woheller69/browser#32]
![Screenshot_2024-02-03-10-21-22-319_org woheller69 browser](https://github.com/woheller69/browser/assets/148094943/d3b7c3bc-269e-493e-80ab-fb36e7505b4f)

**Comment by woheller69** [comment]
by default it switches automatically with your system. This looks like a mixture between light and dark mode, which should not exist

**Comment by woheller69** [comment]
I think I fixed it. Please try.

Backup app data in settings
Uninstall
Remove .zip and install
Restore app data

[app-release.apk.zip](https://github.com/woheller69/browser/files/14152255/app-release.apk.zip)

**Comment by woheller69** [comment]
-> V2.6

**Comment by LISvar** [comment]
🎖

**Comment by woheller69** [comment]
Long click thre dots -> moon symbol

**Comment by LISvar** [comment]
ouuu  yes! It's great! Great app, at all ... 🏆🏆🏆
