### ISSUE TITLE
Give us web dev tools.

### ISSUE THREAD

**Issue by Dilihapu** [woheller69/browser#37]
Firstly, thank you very much give us FOSSly. And I love this app.
I wanted web dev tools for my works. So I request PLZ give us web dev tools like desktop (chrome, firefox, edge).

•view source code
•Element
•editable elements and source code.
•console etc..
if like and if you can please give us feature.
thanks!!!

**Comment by woheller69** [comment]
view source is there. But I will not implement more dev tools

**Comment by Dilihapu** [comment]
Thank you your response. Yes, but tools are important for androind web developers (haven't desktop computers). best dev tools are developed not yet for android. So if there dev tools are the best. Ok, your decision!!!?
THANK YOU!

**Comment by Ultrabenosaurus** [comment]
@Dilihapu in some mobile browsers, you can use the Eruda bookmarklet to add dev tools to any page. Unfortunately it doesn't work in FREE Browser or the DuckDuckGo browser, but it does with in Fennec F-Droid. 

https://eruda.liriliri.io/

https://eruda.liriliri.io/docs/

```js
javascript:(function () {var script=document.createElement('script');script.src="//cdn.jsdelivr.net/npm/eruda";document.body.appendChild(script); script.onload = function () { eruda.init() } })();
```
