### ISSUE TITLE
question about sound playing

### ISSUE THREAD

**Issue by causalcat** [woheller69/browser#38]
hi I would like to ask how I can have some sound playing, not on youtube but in general, through free browser while my screen is off. It is android on xiaomi that I am using.

Thanks!

**Comment by woheller69** [comment]
It usually works for a while. Then Android power management kicks in and stops it ...
In case of youtube I would suggest NewPipe

**Comment by causalcat** [comment]
Thanks it is not youtube but in any site. Is there any way to change this in the android power management?

Στις 7 Μαρτίου 2024 1:32:03 μ.μ. CET, ο/η woheller69 ***@***.***> έγραψε:

**Comment by woheller69** [comment]
no. But you can dim the screen and leave it on...
