### ISSUE TITLE
Fails to render SVG in HTML in night mode

### ISSUE THREAD

**Issue by StevanWhite** [woheller69/browser#39]
The browser fails to render the embedded SVG in the attached example, when in Night mode.

To see this, first either

- set the system to night mode (Android 11+) and set Free Browser's UI to follow the system, or
- set the Free Browser UI to night mode directly

unzip the attached file, and open it with an Android file manager, then choose Free Browser.

The HTML is rendered, but the SVG is not.

The default colors in the SVG should be set similarly to the colors for rendering HTML.
(I think what is going on here is... the color ("black") is changed to white in Night mode, but the background (fill) color ("white") is left as white, resulting in invisible text and lines.)

[five_cell.html.gz](https://github.com/woheller69/browser/files/14536382/five_cell.html.gz)

**Comment by woheller69** [comment]
Is there an URL that does not work? If so, webview probably does not support it

**Comment by StevanWhite** [comment]
? I don't know what URL you refer to.

The issues are: how to handle Night mode, and how best to set colors in embedded SVG, when in night mode.
Here, something has gone so wrong as to make a simple line drawing invisible.

It should also be easy for a programmer to fix.

**Comment by woheller69** [comment]
Night mode is handled by webview. I have no influence on this. It is up to the website to offer a night mode

**Comment by StevanWhite** [comment]
Hi,

We may be misunderstanding one another.

This has nothing to do with websites.

This is about how your app responds to Android 11+ night mode, when rendering an HTML document.

If your app uses a library that misbehaves, you really ought to pass the information up to the maintainers of that library.

**Comment by woheller69** [comment]
Feel free to pass it to Google...

**Comment by woheller69** [comment]
See here, how algorithmic darkening works
https://developer.android.com/develop/ui/views/layout/webapps/dark-theme

**Comment by StevanWhite** [comment]
That is too bad.

**Comment by woheller69** [comment]
Either: WebView renders the content with the dark theme that the content author has defined.

Or: If allowed by the content author, WebView renders the content with a dark theme that is generated using an algorithm.

So its up to the designer of the website to either define a night scheme or to allow/forbid algorithmic darkening
