### ISSUE TITLE
Slowdown with multiple tabs (autoclose tabs)

### ISSUE THREAD

**Issue by anevaiopvn** [woheller69/browser#41]
In my experience the browser slows down to unusable state when tab count starts to exceed 20-30. Closing tabs fixes this.

Maybe you could investigate? As a workaround I propose option to autoclose tabs eg on interval or on app reboot.

If there is another reason for the slowdown, I would still like that option to autoclose tabs.

Cheers

**Comment by woheller69** [comment]
Websites can consume huge amounts of memory. So I suggest you close some windows from time to time.
How many you can open will depend on your phone.
I will not implement autoclose for tabs.

**Comment by anevaiopvn** [comment]
Ok thanks for quick response.

**Comment by anevaiopvn** [comment]
The other option would possibly be to freeze/sleep/unload background tabs, which I actually assumed the browser was doing anyway. Buy anyway, thank you.

**Comment by woheller69** [comment]
if the tabs are closed the browser will completely reload them if needed and potentially consume a lot of data
