### ISSUE TITLE
Userscrips do not work

### ISSUE THREAD

**Issue by sjehuda** [woheller69/browser#42]
Greetings!

I want to test Userscripts with FREE Browser.

I have installed several of my Userscripts and non has worked.

https://openuserjs.org/discuss/FREE_Browser

Please advise.

**Comment by woheller69** [comment]
See Readme for what is supported and what is not.
Switch on Debug to see if your script is being triggered

**Comment by sjehuda** [comment]
According to the "toast" message, it appears that [Proxy Redirect](https://greasyfork.org/en/scripts/465936-proxy-redirect) is the only one that is triggered, and that is it. The behaviour of the Userscript is not realized.

**Comment by sjehuda** [comment]
and that is it. The behaviour of the Userscript is not realized.

**Comment by woheller69** [comment]
Then you need to check if your @match clauses conform to the specification in Readme and make sure not to use @include, etc

**Comment by sjehuda** [comment]
I will do, for the rest of the userscripts.
```
// @match        file:///*
// @match        *://*/*
```

What is the status of GM API?
```
// @grant        GM.getValue
// @grant        GM.registerMenuCommand
// @grant        GM.setValue
// @grant        GM.xmlHttpRequest
// @grant        GM_xmlhttpRequest
```
I do make use of these GM APIs, especially the `GM.getValue` and `GM.setValue` which make Userscripts as usable as "web extensions".

**Comment by woheller69** [comment]
GM API is not supported

**Comment by sjehuda** [comment]
Will it be supported in future?

**Comment by woheller69** [comment]
not planned

**Comment by sjehuda** [comment]
1) Are PRs for supporting GM API acceptable?

2) Should a [feed renderer](https://greasyfork.org/scripts/465932-newspaper), which has extra features based on GM API that are _optional_, be working with FREE Browser?

**Comment by woheller69** [comment]
I think that is quite complex and only very few people will be using it.
Not sure how intrusive that would be. The browser works great right now and I do not want to break things...
