### ISSUE TITLE
Bug:  When "Force stop" is performed, the app should forget history

### ISSUE THREAD

**Issue by javierxio** [woheller69/browser#46]
Hello. I was looking at a webpage and then I wanted to quit out of the program. Due to I got into a fullscreen mode and I lost the browser buttons, I had to do a "Force Stop" from within the Android settings menu. On the next launch of the Free Browser, the app reopened the last URL where I had forced stopped.

Steps to reproduce:

1. Navigate to yahoo.com
2. Long press on FREE Browser app icon to open App Info
3. Click, "Force stop"
4. Now, relaunch the app

Current behavior:

1. Currently, the app will resume and navigate to yahoo.com on relaunch

Expected behavior:

1. Should load the default homepage.

**Comment by woheller69** [comment]
Actually its a feature. It was built in because some Androids force stop apps in background
