### ISSUE TITLE
Support for Brazilian Portuguese

### ISSUE THREAD

**Issue by ticoeteco23gb** [woheller69/browser#47]
Hello, I have just opened this browser. The features are very promising, and it has support for SearX, but one thing that is annoying me is that the language is European Portuguese, and it's not the dialect that I'm used to, I didn;t find any options to switvhing to english, so I'm kindly asking to add support to the Brazilian Portuguese, since the two languages have many differences between each other (Example: Screen: 🇧🇷tela - 🇵🇹ecrã). Thanks for the browser, it may be useful to me.

**Comment by woheller69** [comment]
https://github.com/woheller69/browser/blob/newmaster/app/src/main/res/values-pt/strings.xml

If you want to contribute you can modify the attached strings.xml file and upload it here.

**Comment by ticoeteco23gb** [comment]
How can I upload the file? I am not experienced with using GitHub.

**Comment by woheller69** [comment]
Just attach to a message here. "Paste, drop, or click...."

**Comment by ticoeteco23gb** [comment]
[strings.zip](https://github.com/user-attachments/files/18429933/strings.zip)
Hello! Sorry for the delay, but I finally finished the translation to Brazilian Portuguese, I've uploaded it in ZIP because GitHub doesn't supports XML. Thank you for this opportunity! If there's anything that I should change, please let me know.

**Comment by woheller69** [comment]
thanks
