### ISSUE TITLE
Changing browser settings clears tabs

### ISSUE THREAD

**Issue by browser2000** [woheller69/browser#49]
browser version: 2.8
webview version: 126
[logcat.log](https://github.com/user-attachments/files/15884781/logcat.log)

https://github.com/woheller69/browser/assets/173152144/94e9863f-2886-4f9f-9e68-7246262a22c1

**Comment by woheller69** [comment]
Yes, manually closing the browser clears the tabs. This is intened. Most changes in settings also work without closing the app - at least for new tabs.

**Comment by browser2000** [comment]
@woheller69
If this
![MUST](https://github.com/woheller69/browser/assets/173152144/9e5963aa-a789-4b1a-b747-f2b622823076)
 is manually closing the browser, then fuck me and anyone using this browser, I guess...
 
 If it is not needed to click on that after a settings change, then it shouldn't appear in the first place.
 If an action is going to clear the tabs or whatever else, it should clearly state that it is going to do that, not to have 100+ tabs, the browser tell you MUST do something and then you find out that everything is gone.
