### ISSUE TITLE
New features request

### ISSUE THREAD

**Issue by m1trenv0** [woheller69/browser#5]
Auto-generator custom canvas fingerprint/useragent (btw I never found where i can change canvas fingerprint in your browser)
this function will be useful for sites that give certain bonuses for new users (for example, AliExpress)

**Comment by woheller69** [comment]
canvas fingerprint is always spoofed (random) when fingerprint protection is on

**Comment by m1trenv0** [comment]
I need to be able to change it in one click

**Comment by woheller69** [comment]
you can write your own Greasemonkey script and run it as needed.
I will not implement it.
