### ISSUE TITLE
Run on Android 7.0 (APK 24)

### ISSUE THREAD

**Issue by StevanWhite** [woheller69/browser#51]
The `minSdkVersion` is set to 29 (Android 10).  That's like, just yesterday!

For my purposes, I want API 24 (Android 7.0), which goes back 10 years.
This can be achieved by just a few modifications.

(As far as the current libraries go, that could be dialed back to 21, but it would take
a lot of work to get it running properly.)

## API 34

Runs OK out of the box.

## API 25

Best to first do a Code--> Inspect Code, which will show some errors 
concerning new function calls on old devices.  The following explains how
I dealt with them.

First problem in AdBlock.java, at the line

       copyFile(manager.open(FILE), Files.newOutputStream(file.toPath()));

Replaced that line with

       InputStream newFile = manager.open(FILE);
       if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.O )
            copyFile(newFile, Files.newOutputStream(file.toPath()));
       else
            copyFile(newFile, new FileOutputStream(file.toString()));

Next problem, in BannerBlock.java, at the line

        String jsonDataString =  new String(Files.readAllBytes(Paths.get(file.getPath())));

Older versions of Java didn't have this nice `readAllBytes()`, but this will do:

        String jsonDataString = "";
        if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.O ) {
            Path jsonFilePath = Paths.get(file.getPath());
            jsonDataString = new String(Files.readAllBytes(jsonFilePath));
        }
        else {
            try(RandomAccessFile f = new RandomAccessFile(file, "r")) {
                final long length = f.length();
                if( length < Integer.MAX_VALUE ) {
                    byte[] bytes = new byte[(int)length];
                    f.readFully( bytes );
                    jsonDataString = new String(bytes);
                }
                else
                    Log.e( "loadHosts", "JSON file too long" );
            }
        }

In BackupUnit.java, insert this static helper method:

    private static OutputStream getOutputStream(@NonNull File extractedFile ) throws FileNotFoundException, IOException {
        if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.O ) {
            return Files.newOutputStream(extractedFile.toPath());
        }
        else {
            return new FileOutputStream(extractedFile.toString());
        }
    }
    
and replace the line

    try (OutputStream outputStream = Files.newOutputStream(extractedFile.toPath())) {

with

    try (OutputStream outputStream = getOutputStream( extractedFile )) {

In HelperUnit.java, all the `ShortcutManager.isRequestPinShortcutSupported()`
stuff makes no sense on pre-Android 8 devices, so disabled it with

    if( Build.VERSION.SDK_INT >= Build.VERSION_CODES.O )

Likewise, in NinjaWebView.java, calls to

    this.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_YES);

and

    webSettings.setSafeBrowsingEnabled(true);

are Android 8+, so disable those for earlier versions, the same way.

## API 24

In BrowserUnit.java, `clearBookmark()`, likewise disable with

    if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N_MR1 ) {
        ShortcutManager shortcutManager = context.getSystemService(ShortcutManager.class);
        Objects.requireNonNull(shortcutManager).removeAllDynamicShortcuts();
    }

I tested this, to the best of my abilities, on emulators and devices running Android 7.0, 7.1, and 7.1.1,
as well as an emulator running Android 14, an a phone running Android 12.
I saw no bugs, performing basic activities.  In fact, it worked great!

Cheers!

**Comment by woheller69** [comment]
I have no plan to change the minSdk downwards in this case. But if you have it running, feel free to upload the apk (you need to nename it to .zip) here, so others can use it.

**Comment by StevanWhite** [comment]
I'm not surprised tat you had no plan to do this.  This is a request from an appreciative user.

I wouldn't call it a "downgrade".  It is an expansion of your target users.

You have seen the changes.  They refer to your existing code base, and are very limited in scope, and very easy to understand.

If you like, give me  instructions, and I can push the changes to you.

Regarding an APK... wouldn't that need to be signed?  By whom?  Me?

**Comment by woheller69** [comment]
I currently have 17 apps on F-Droid and do not want to increase my maintenance effort for old Android versions.
You can upload a signed apk if you like.

**Comment by mk13v** [comment]
https://creativecommons.org/publicdomain/zero/1.0/deed.enhttps://docs.github.com/es/site-policy/github-terms/github-terms-of-servicehttps://docs.github.com/es/support/contacting-github-supportlahttps://codeql.github.com/docs/https://docs.github.com/es/code-security/codeql-for-vs-codehttps://support.github.com/request/landinghttps://github.com/sponsors/explore1964
Resultados de la búsqueda para
"En%20algunos%20casos,%20terceros%20desidentifican,%20agrupan%20o%20anonimizan%20la%20informaci%C3%B3n%20para%20que%20ya%20no%20identifique%20a%20personas%20antes%20de%20ponerla%20a%20nuestra%20disposici%C3%B3n.%20Usamos%20esta%20informaci%C3%B3n%20como%20se%20describe%20a%20continuaci%C3%B3n%20sin%20intentar%20volver%20a%20identificar%20a%20las%20personas.Toma%20el%20controlAdministra%20la%20informaci%C3%B3n%20que%20recopilamos%20sobre%20tiCentro%20de%20privacidadVolver%20arriba%C2%BFC%C3%B3mo%20usamos%20t"
GitHub Desktop / Instalación y autenticación /  Autenticación en GitHub en
GitHub Desktop Puedes acceder de formahttps://
creativecommons.org/publicdomain/zero/1.0/deed.enhttps://docs.github.com/es/site-policy/github-terms/github-terms-of-servicehttps://docs.github.com/es/support/contacting-github-supportlahttps://codeql.github.com/docs/https://docs.github.com/es/code-security/codeql-for-vs-codehttps://github.com/sponsors/explore1964
Resultados de la búsqueda para
"En%20algunos%20casos,%20terceros%20desidentifican,%20agrupan%20o%20anonimizan%20la%20informaci%C3%B3n%20para%20que%20ya%20no%20identifique%20a%20personas%20antes%20de%20ponerla%20a%20nuestra%20disposici%C3%B3n.%20Usamos%20esta%20informaci%C3%B3n%20como%20se%20describe%20a%20continuaci%C3%B3n%20sin%20intentar%20volver%20a%20identificar%20a%20las%20personas.Toma%20el%20controlAdministra%20la%20informaci%C3%B3n%20que%20recopilamos%20sobre%20tiCentro%20de%20privacidadVolver%20arriba%C2%BFC%C3%B3mo%20usamos%20t"
GitHub Desktop / Instalación y autenticación /  Autenticación en GitHub en
GitHub Desktop Puedes acceder de forma segura a los recursos de tu cuenta
en GitHub Desktop si te autenticas con GitHub. Acerca de la autenticación
Para mantener la seguridad GitHub Actions / Guías de seguridad /  Uso de
secretos en Acciones de GitHub confidencial en tu organización, repositorio
o entornos de repositorio. Acerca de los secretos Los secretos son
variables que se crean en una organización GitHub Actions / Ejecutores
hospedados en GitHub / Acerca de los ejecutores hospedados en GitHub /
Acerca de los ejecutores hospedados en GitHub Información general de
ejecutores hospedados en GitHub Los ejecutores son las máquinas que
ejecutan trabajos en un flujo de trabajo de GitHub Actions. Por Las
organizaciones / Seguridad de la organización / Administrar 2FA /  Requerir
autenticación en dos fases en la organización usuarios que contribuyan con
código en GitHub.com habiliten una o varias formas de autenticación en dos
fases (2FA). Si estás en un grupo elegible, recibirás Las organizaciones /
Administrar la configuración de la organización /  Configuración de redes
privadas para los ejecutores hospedados en GitHub en su organización
hospedados en GitHub con una red privada de Azure en su organización.
Acerca de la configuración de la red privada para ejecutores hospedados en
GitHub Para Las organizaciones / Administrar la configuración de la
organización /  Solución de problemas de configuraciones de redes privadas
de Azure para ejecutores hospedados en GitHub en su organización alojados
en GitHub con una Azure VNET. Solución de problemas relacionados con la
configuración de las redes privadas para los ejecutores hospedados en
GitHub Contribuir a GitHub Docs / Tu entorno de trabajo /  Trabajo en
GitHub Docs en un codespace Codespaces a fin de trabajar en documentación
para GitHub Docs. Acerca de GitHub Codespaces GitHub Codespaces permite
trabajar en un entorno de desarrollo Codespaces / Desarrollar en un
codespace /  Uso de GitHub Codespaces en Visual Studio Code Puedes realizar
tareas de desarrollo en tu codespace directamente en Visual Studio Code
conectando la extensión GitHub Codespaces con tu cuenta de GitHub Las
organizaciones / Administrar la configuración de la organización /  Acerca
de las redes privadas de Azure para ejecutores hospedados en GitHub en su
organización ejecutores hospedados en GitHub en sus redes virtuales (VNET)
de Azure. Acerca de la configuración de la red privada para ejecutores
hospedados en GitHub Puede Codespaces / Desarrollar en un codespace /
Desarrollar en un codespace Puedes trabajar en un codespace mediante el
explorador, Visual Studio Code, un IDE de JetBrains o en un shell de
comandos. Notas: El uso de GitHub Codespaces Ayuda y soporte técnico ¿Le
ayudó este documento?  Directiva de privacidad ¿Aún necesitahttps://
github.com/features/issues Centro de ayuda   Cómo resguardar tu
跳至主內容關閉持續捲動功能 無障礙說明 無障礙工具意見回饋 Google 20170620X   全部 購物 圖片 影片 新聞 更多 工具 安全搜尋
濾除 關閉 模糊處理  伊勢市M様邸 浴室リフォーム システムバス設置工事|三重県津市 松浦建築 http://matsuura-k.jp ›
blog › 2017

**Comment by StevanWhite** [comment]
You mean, I should sign an APK with my own certificate, and upload that?

My aim here was to *reduce* your load.  I am offering to make changes *for* you.

**Comment by woheller69** [comment]
yes,  just upload the APK. That is zero effort for me.

**Comment by mk13v** [comment]
Ok, thanks.

**Comment by mk13v** [comment]
Woheller 69 ocupo un paro ahora si ocupo dinero  mi familia va regresar
conmigo hoy se acabo la paciencia necesario q avises a todas las estancias
y tienes q ayudarme Compartimos una rama somos socios lo mio es tuyo pero
no me dejes abajo

**Comment by mk13v** [comment]
Alrato te mando unos formatos q tengo

**Comment by mk13v** [comment]
Jugamos limpio socia

**Comment by mk13v** [comment]
Y puedes revisar unos formatos y no se si tu ya ayas cobrado si no lo vamos
a repartirc50 50

**Comment by mk13v** [comment]
Y para q sigas trabajando y creando más y seas la mejor con los
***@***.***ítica de Privacidadversión
2.22.13.77): SO Android 4.0.3 o posterior.
Centro de ayuda

Información sobre las comunidades
Las comunidades de WhatsApp reúnen a los miembros en grupos por temas.
Cualquier persona puede crear una comunidad de WhatsApp. Puedes crear
nuevos grupos basados en temas o añadir grupos de WhatsApp existentes.

Los administradores de la comunidad pueden contactar a los miembros con
actualizaciones importantes mediante el envío de avisos. y los miembros
pueden explorar los grupos que les interesen y chatear en ellos a fin de
mantenerse conectados.
Los miembros también pueden recibir novedades que se envíen a toda la
comunidad También pueden organizar fácilmente grupos de discusión sobre los
temas que les interesen.
Los mensajes y las llamadas personales en las comunidades cuentan siempre
con cifrado de extremo a extremo. Nadie más, ni siquiera WhatsApp, puede
leerlos o escucharlos.
Estas son algunas cosas útiles que puedes hacer en los grupos que forman
parte de las comunidades:
Crear eventos
Compartir encuestas
Reaccionar a mensajes
Compartir archivos
Usar controles para administradores
Responder a avisos de la comunidad
Recursos relacionados:
Cómo crear una comunidad
Información acerca del grupo de avisos de la comunidad
Centro de aprendizaje de Comunidades

¿Esto responde a tu pregunta?
Usar WhatsApp
Funciones
Descargar
Nosotros
Business
Seguridad
Privacidad y condiciones
Contacto
Contáctanos
Facebook
X (Twitter)
Logotipo de From Meta
© 2024 WhatsAppElimina participantes

Los administradores pueden eliminar grupos o miembros de grupos
problemáticos de una comunidad.

Elimina chats

Los administradoreshttps://
www.whatsapp.com/communityhttps://m.facebook.com/nt/screen/?params=%7B"phase"%3A"unauthenticated"%2C"step"%3A"stepper_confirmation"%2C"is_eligible_for_challenges"%3Atrue%7D&path=%2Fnt%2Fcheckpoint%2F828281030927956%2Fhelp_modal&stateRe:
Undeliverable: Re: Undeliverable: Re: Tu código de un solo
usoGraciasMostrar texto citado"PayPal Cashback Mastercard®"
https://www.paypal.com/credit-application/co/landing?present=clpCOB32CONTROLSINQUIRY&track=cltMICROSITE"PayPal
Cashback Mastercard®"
https://www.paypal.com/credit-application/co/landing?present=clpCOB32CONTROLSINQUIRY&track=cltMICROSITEhttps://www.paypal.com/us/digital-wallet/manage-money/paypal-cashback-mastercardhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmWF9213521NWF9213521NREWARDShttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmWF9213521NWF9213521NREWARDS
TERMS AND CONDITIONS FOR PAYPAL CASHBACK MASTERCARD® OR PAYPAL CASHBACK
WORLD MASTERCARD® Card Account Rewards Program (“Program”) REWARDS SUMMARY
Please review the details in the full Program terms and conditions below
(“Program Terms”). Earn Automatically earn Cash Rewards on each Eligible
PurchaseMASTERCARD®REWARDS TERMS AND CONDITIONS FOR PAYPAL CASHBACK
MASTERCARD® OR PAYPAL CASHBACK WORLD MASTERCARD® Card Account Rewards
Program (“Program”) REWARDS SUMMARY Please review the details in the full
Program terms and conditions below (“Program Terms”). Earn Automatically
earn Cash Rewards on each Eligible Purchase: Earn 3% on Eligible Purchases
you make using your Card Account through your PayPal account (online or
in-store), or when you use your Card Account to send money to other PayPal
users through your PayPal account. Earn 2% on Eligible Purchases made
everywhere else that Mastercard is accepted until July 31, 2024 and
thereafter 1.5%. Earn 2% on any Eligible Purchases made by any authorized
user(s) until July 31, 2024 and thereafter 1.5%. In the event an authorized
user is, in the future, able to add their Card to their PayPal account,
then Eligible Purchases made by such authorized user through their PayPal
account or when sending money to other PayPal users through their PayPal
account will earn 3% Cash Rewards and Eligible Purchases made everywhere
else that Mastercard is accepted will continue to earn 2% Cash Rewards
until July 31, 2024 and thereafter 1.5%. An adjustment may reduce Cash
Rewards in an amount up to the amount of any Cash Rewards originally earned
on the Eligible Purchase. How to Redeem Cash Rewards Cash Rewards earned
will be available for you to transfer to your PayPal account within
approximately three days after each Eligible Purchase is made, provided
your Card Account and PayPal account are open and in good standing and
linked to each other. How to Use Cash Rewards Cash Rewards can be used once
they are transferred by you to your PayPal account. If you have a PayPal
Balance account, the Rewards can be used to make payments, make purchases,
send money to other PayPal users, or transferred to your bank account or
debit card linked to your PayPal account. If you do not have a PayPal
Balance account, the Rewards can only be transferred to your bank account
or debit card linked to your PayPal account. As a PayPal Cashback
Mastercard® or PayPal Cashback World Mastercard® (each a “Card”) Account
(“Card Account”) Accountholder, you will earn cash back rewards (referred
to as “Cash Rewards” or “Cash Back”) on Eligible Purchases made by you
(subject to your available credit), the person to whom the Card Account was
issued (“Accountholder” or “you”) or the authorized users on your Card
Account, as set forth below. The amount of Cash Rewards earned is
determined by the Card Account user, whether the payment is made through
the PayPal account, and the amount of Eligible Purchases made on a daily
basis. Cash Rewards may be reduced by any applicable Cash Rewards
adjustments. Synchrony Bank (“Synchrony”) is the issuer of the Card
Account, and it is only available to Accountholders who have an open PayPal
account to which the Card Account is linked, and both accounts must be
maintained in good standing. Your participation in the Program is subject
to these Program Terms. “Eligible Purchases” means the dollar amount of
purchases of goods and services made using your Card Account. Eligible
Purchases also means the dollar amount of transactions when you use the
Card Account to send money to another PayPal user through your PayPal
account. Eligible Purchases do not include balance transfers, cash
advances, convenience checks, disputed transactions, unauthorized or
fraudulent transactions, interest, fees, as applicable, or any other
transactions that Synchrony may determine in its sole discretion are not
eligible to earn Cash Rewards. Earn Cash Rewards on Eligible Purchases. At
thhttphttps://m.facebook.com/nt/screen/?params=%7B"phase"%3A"unauthenticated"%2C"step"%3A"stepper_confirmation"%2C"is_eligible_for_challenges"%3Atrue%7D&path=%2Fnt%2Fcheckpoint%2F828281030927956%2Fhelp_modal&stateRe:
Undeliverable: Re: Undeliverable: Re: Tu código de un solo uso Gracias
Mostrar texto citado "PayPal Cashback Mastercard®"
https://www.paypal.com/credit-application/co/landing?present=clpCOB32CONTROLSINQUIRY&track=cltMICROSITE"PayPal
Cashback Mastercard®"
https://www.paypal.com/credit-application/co/landing?present=clpCOB32CONTROLSINQUIRY&track=cltMICROSITEhttps://www.paypal.com/us/digital-wallet/manage-money/paypal-cashback-mastercardhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmWF9213521NWF9213521NREWARDShttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmWF9213521NWF9213521NREWARDS
TERMS AND CONDITIONS FOR PAYPAL CASHBACK MASTERCARD® OR PAYPAL CASHBACK
WORLD MASTERCARD® Card Account Rewards Program (“Program”) REWARDS SUMMARY
Please review the details in the full Program terms and conditions below
(“Program Terms”). Earn Automatically earn Cash Rewards on each Eligible
PurchaseMASTERCARD®REWARDS TERMS AND CONDITIONS FOR PAYPAL CASHBACK
MASTERCARD® OR PAYPAL CASHBACK WORLD MASTERCARD® Card Account Rewards
Program (“Program”) REWARDS SUMMARY Please review the details in the full
Program terms and conditions below (“Program Terms”). Earn Automatically
earn Cash Rewards on each Eligible Purchase: Earn 3% on Eligible Purchases
you make using your Card Account through your PayPal account (online or
in-store), or when you use your Card Account to send money to other PayPal
users through your PayPal account. Earn 2% on Eligible Purchases made
everywhere else that Mastercard is accepted until July 31, 2024 and
thereafter 1.5%. Earn 2% on any Eligible Purchases made by any authorized
user(s) until July 31, 2024 and thereafter 1.5%. In the event an authorized
user is, in the future, able to add their Card to their PayPal account,
then Eligible Purchases made by such authorized user through their PayPal
account or when sending money to other PayPal users through their PayPal
account will earn 3% Cash Rewards and Eligible Purchases made everywhere
else that Mastercard is accepted will continue to earn 2% Cash Rewards
until July 31, 2024 and thereafter 1.5%. An adjustment may reduce Cash
Rewards in an amount up to the amount of any Cash Rewards originally earned
on the Eligible Purchase. How to Redeem Cash Rewards Cash Rewards earned
will be available for you to transfer to your PayPal account within
approximately three days after each Eligible Purchase is made, provided
your Card Account and PayPal account are open and in good standing and
linked to each other. How to Use Cash Rewards Cash Rewards can be used once
they are transferred by you to your PayPal account. If you have a PayPal
Balance account, the Rewards can be used to make payments, make purchases,
send money to other PayPal users, or transferred to your bank account or
debit card linked to your PayPal account. If you do not have a PayPal
Balance account, the Rewards can only be transferred to your bank account
or debit card linked to your PayPal account. As a PayPal Cashback
Mastercard® or PayPal Cashback World Mastercard® (each a “Card”) Account
(“Card Account”) Accountholder, you will earn cash back rewards (referred
to as “Cash Rewards” or “Cash Back”) on Eligible Purchases made by you
(subject to your available credit), the person to whom the Card Account was
issued (“Accountholder” or “you”) or the authorized users on your Card
Account, as set forth below. The amount of Cash Rewards earned is
determined by the Card Account user, whether the payment is made through
the PayPal account, and the amount of Eligible Purchases made on a daily
basis. Cash Rewards may be reduced by any applicable Cash Rewards
adjustments. Synchrony Bank (“Synchrony”) is the issuer of the Card
Account, and it is only available to Accountholders who have an open PayPal
account to which the Card Account is linked, and both accounts must be
maintained in good standing. Your participation in the Program is subject
to these Program Terms. “Eligible Purchases” means the dollar amount of
purchases of goods and services made using your Card Account. Eligible
Purchases also means the dollar amount of transactions when you use the
Card Account to send money to another PayPal user through your PayPal
account. Eligible Purchases do not include balance transfers, cash
advances, convenience checks, disputed transactions, unauthorized or
fraudulent transactions, interest, fees, as applicable, or any other
transactions that Synchrony may determine in its sole discretion are not
eligible to earn Cash Rewards. Earn Cash Rewards on Eligible Purchases. At
thhttps://
m.facebook.com/nt/screen/?params=%7B%22phase%22%3A%22unauthenticated%22%2C%22step%22%3A%22stepper_confirmation%22%2C%22is_eligible_for_challenges%22%3Atrue%7D&path=%2Fnt%2Fcheckpoint%2F828281030927956%2Fhelp_modal&stateRe:%20Undeliverable:%20Re:%20Undeliverable:%20Re:%20Tu%20c%C3%B3digo%20de%20un%20solo%20usoGraciasMostrar%20texto%20citado%22PayPal%20Cashback%20Mastercard%C2%AE%22%20https://www.paypal.com/credit-application/co/landing?present=clpCOB32CONTROLSINQUIRY&track=cltMICROSITE%22PayPal%20Cashback%20Mastercard%C2%AE%22%20https://www.paypal.com/credit-application/co/landing?present=clpCOB32CONTROLSINQUIRY&track=cltMICROSITEhttps://www.paypal.com/us/digital-wallet/manage-money/paypal-cashback-mastercardhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmWF9213521NWF9213521NREWARDShttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmhttps://www.synchronycredit.com/gecrbterms/html/PayPalCashbackRewardsTerms.htmWF9213521NWF9213521NREWARDS%20TERMS%20AND%20CONDITIONS%20FOR%20PAYPAL%20CASHBACK%20MASTERCARD%C2%AE%20OR%20PAYPAL%20CASHBACK%20WORLD%20MASTERCARD%C2%AE%20%20Card%20Account%20Rewards%20Program%20(%E2%80%9CProgram%E2%80%9D)%20%20REWARDS%20SUMMARY%20%20%20Please%20review%20the%20details%20in%20the%20full%20Program%20%20%20%20terms%20and%20conditions%20below%20(%E2%80%9CProgram%20Terms%E2%80%9D).%20%20Earn%20Automatically%20earn%20Cash%20Rewards%20on%20each%20Eligible%20PurchaseMASTERCARD%C2%AEREWARDS%20TERMS%20AND%20CONDITIONS%20FOR%20PAYPAL%20CASHBACK%20MASTERCARD%C2%AE%20OR%20PAYPAL%20CASHBACK%20WORLD%20MASTERCARD%C2%AE%20%20Card%20Account%20Rewards%20Program%20(%E2%80%9CProgram%E2%80%9D)%20%20REWARDS%20SUMMARY%20%20%20Please%20review%20the%20details%20in%20the%20full%20Program%20%20%20%20terms%20and%20conditions%20below%20(%E2%80%9CProgram%20Terms%E2%80%9D).%20%20Earn%20Automatically%20earn%20Cash%20Rewards%20on%20each%20Eligible%20Purchase:%20%20Earn%203%%20on%20Eligible%20Purchases%20you%20make%20using%20your%20Card%20Account%20through%20your%20PayPal%20account%20(online%20or%20in-store),%20or%20when%20you%20use%20your%20Card%20Account%20to%20send%20money%20to%20other%20PayPal%20users%20through%20your%20PayPal%20account.%20Earn%202%%20on%20Eligible%20Purchases%20made%20everywhere%20else%20that%20Mastercard%20is%20accepted%20until%20July%2031,%202024%20and%20thereafter%201.5%.%20Earn%202%%20on%20any%20Eligible%20Purchases%20made%20by%20any%20authorized%20user(s)%20until%20July%2031,%202024%20and%20thereafter%201.5%.%20In%20the%20event%20an%20authorized%20user%20is,%20in%20the%20future,%20able%20to%20add%20their%20Card%20to%20their%20PayPal%20account,%20then%20Eligible%20Purchases%20made%20by%20such%20authorized%20user%20through%20their%20PayPal%20account%20or%20when%20sending%20money%20to%20other%20PayPal%20users%20through%20their%20PayPal%20account%20will%20earn%203%%20Cash%20Rewards%20and%20Eligible%20Purchases%20made%20everywhere%20else%20that%20Mastercard%20is%20accepted%20will%20continue%20to%20earn%202%%20Cash%20Rewards%20until%20July%2031,%202024%20and%20thereafter%201.5%.%20An%20adjustment%20may%20reduce%20Cash%20Rewards%20in%20an%20amount%20up%20to%20the%20amount%20of%20any%20Cash%20Rewards%20originally%20earned%20on%20the%20Eligible%20Purchase.%20How%20to%20Redeem%20Cash%20Rewards%20Cash%20Rewards%20earned%20will%20be%20available%20for%20you%20to%20transfer%20to%20your%20PayPal%20account%20within%20approximately%20three%20days%20after%20each%20Eligible%20Purchase%20is%20made,%20provided%20your%20Card%20Account%20and%20PayPal%20account%20are%20open%20and%20in%20good%20standing%20and%20linked%20to%20each%20other.%20%20How%20to%20Use%20Cash%20Rewards%20Cash%20Rewards%20can%20be%20used%20once%20they%20are%20transferred%20by%20you%20to%20your%20PayPal%20account.%20If%20you%20have%20a%20PayPal%20Balance%20account,%20the%20Rewards%20can%20be%20used%20to%20make%20payments,%20make%20purchases,%20send%20money%20to%20other%20PayPal%20users,%20or%20transferred%20to%20your%20bank%20account%20or%20debit%20card%20linked%20to%20your%20PayPal%20account.%20If%20you%20do%20not%20have%20a%20PayPal%20Balance%20account,%20the%20Rewards%20can%20only%20be%20transferred%20to%20your%20bank%20account%20or%20debit%20card%20linked%20to%20your%20PayPal%20account.%20%20As%20a%20PayPal%20Cashback%20Mastercard%C2%AE%20or%20PayPal%20Cashback%20World%20Mastercard%C2%AE%20(each%20a%20%E2%80%9CCard%E2%80%9D)%20Account%20(%E2%80%9CCard%20Account%E2%80%9D)%20Accountholder,%20you%20will%20earn%20cash%20back%20rewards%20(referred%20to%20as%20%E2%80%9CCash%20Rewards%E2%80%9D%20or%20%E2%80%9CCash%20Back%E2%80%9D)%20on%20Eligible%20Purchases%20made%20by%20you%20(subject%20to%20your%20available%20credit),%20the%20person%20to%20whom%20the%20Card%20Account%20was%20issued%20(%E2%80%9CAccountholder%E2%80%9D%20or%20%E2%80%9Cyou%E2%80%9D)%20or%20the%20authorized%20users%20on%20your%20Card%20Account,%20as%20set%20forth%20below.%20The%20amount%20of%20Cash%20Rewards%20earned%20is%20determined%20by%20the%20Card%20Account%20user,%20whether%20the%20payment%20is%20made%20through%20the%20PayPal%20account,%20and%20the%20amount%20of%20Eligible%20Purchases%20made%20on%20a%20daily%20basis.%20Cash%20Rewards%20may%20be%20reduced%20by%20any%20applicable%20Cash%20Rewards%20adjustments.%20Synchrony%20Bank%20(%E2%80%9CSynchrony%E2%80%9D)%20is%20the%20issuer%20of%20the%20Card%20Account,%20and%20it%20is%20only%20available%20to%20Accountholders%20who%20have%20an%20open%20PayPal%20account%20to%20which%20the%20Card%20Account%20is%20linked,%20and%20both%20accounts%20must%20be%20maintained%20in%20good%20standing.%20Your%20participation%20in%20the%20Program%20is%20subject%20to%20these%20Program%20Terms.%20%20%E2%80%9CEligible%20Purchases%E2%80%9D%20means%20the%20dollar%20amount%20of%20purchases%20of%20goods%20and%20services%20made%20using%20your%20Card%20Account.%20Eligible%20Purchases%20also%20means%20the%20dollar%20amount%20of%20transactions%20when%20you%20use%20the%20Card%20Account%20to%20send%20money%20to%20another%20PayPal%20user%20through%20your%20PayPal%20account.%20Eligible%20Purchases%20do%20not%20include%20balance%20transfers,%20cash%20advances,%20convenience%20checks,%20disputed%20transactions,%20unauthorized%20or%20fraudulent%20transactions,%20interest,%20fees,%20as%20applicable,%20or%20any%20other%20transactions%20that%20Synchrony%20may%20determine%20in%20its%20sole%20discretion%20are%20not%20eligible%20to%20earn%20Cash%20Rewards.%20%20Earn%20Cash%20Rewards%20on%20Eligible%20Purchases.%20%20At%20thhttps://m.facebook.com/nt/screen/?params=%7B%22phase%22%3A%22unauthenticated%22%2C%22step%22%3A%22stepper_confirmation%22%2C%22is_eligible_for_challenges%22%3Atrue%7D&path=%2Fnt%2Fcheckpoint%2F828281030927956%2Fhelp_modal&statehttps://www.marketbeat.com/scripts/redirect.aspx?MessageQueueID=24459&UserID=12864355&interstitial=1&SubjectLineID=0&RedirectURL=https%3a%2f%2fwww.marketbeat.com%2fstock-ideas%2fdell-and-super-micro-computer-musks-favorite-ai-hardware-stocks%2f

Ayuda
Entendemos que es preocupante saber que alguien puede haber ingresado a tu
cuenta, así que tomamos las medidas necesarias para protegerte.
¿Por qué se bloqueó mi cuenta?

¿Cómo vuelvo a ingresar a Facebook?

Te ayudaremos a volver a ingresar a tu cuenta y nos aseguraremos de que no
se hayan realizado cambios en ella. No necesitas pedir asistencia en ningún
otro sitio. Nosotros te guiaremos con unos pasos sencillos para que lo
hagas ahora mismo.

Confirma que esta es tu cuenta
Como es posible que otra persona haya accedido a tu cuenta, debemos
confirmar que eres el propietario de la cuenta antes de continuar.

Protege tus datos de inicio de sesión
Comprueba todos los correos electrónicos y números de teléfono de tu cuenta
y te ayudaremos a eliminar los antiguos o desconocidos.
¿Qué ocurre si no desbloqueo mi cuenta?


Cambiar idioma
Español

Cerrar sesión"Sugerencias para completar los pasos de recuperación de la
cuenta - Ayuda de Cuenta de Google"
https://support.google.com/accounts/answer/7299973?hl=es-419

**Comment by mk13v** [comment]
Ocupamos seguir actualizando
