### ISSUE TITLE
Website rendering issues

### ISSUE THREAD

**Issue by Machion** [woheller69/browser#52]
I am using your browser on a Moto G100 with Android 14/LineageOS 21. 
When I'm browsing certain sites, the structure, mostly pictures seem out of place or have a strange zoom. 
One example would be: I go on duckduckgo.com and do a picture search. When clicking on a picture in the grid to enlarge it, it's out of center (only partially visible).

**Comment by woheller69** [comment]
Such things can happen with fingerprint protection switched on because the server cannot read your screen size.

**Comment by Machion** [comment]
Is this an option somewhere in the settings of the browser or the OS? 
I am using Fulguris browser side by side with yours, but there are no such issues. Both use System Webview right?

**Comment by woheller69** [comment]
Fingerprint protection is a privacy feature of my browser, and yes there is button to switch it off. See instructions

**Comment by Machion** [comment]
Yes now it works. Thanks!
