### ISSUE TITLE
Mobile mode is not working 

### ISSUE THREAD

**Issue by drakegao** [woheller69/browser#56]
Hi Team, I really like this browser and so far I found that a lot of modern websites including search.brave.com is not working on a mobile view. Many websites become the desktop view in this browser. Is there anyway to set the settings? Also it would be nice to include the brave search engine too.  I am using Android 14

**Comment by woheller69** [comment]
It may have to do with protection against fingerprinting because websites cannot access your screen size.

You can set a user defined search engine in settings.

**Comment by drakegao** [comment]
Thanks. So mozailla fingerprint blocking, right? It is for protection. By the way, is there anyway way to update the add blocker or I can install somewhere? Pages like Animesurge can be ad blocked by brave browser but doesn't work here.

Regards
Drake

Sent from Proton Mail Android

-------- Original Message --------
On 8/10/24 3:07 PM, woheller69 wrote:
It may have to do with protection against fingerprinting because websites cannot access your screen size.
You can set a user defined search engine in settings.

**Comment by woheller69** [comment]
Fingerprint protection is not from Mozilla. It is a feature of this browser and can be switched off.

You can select from several adblock lists and can also specify additional domains.

**Comment by drakegao** [comment]
Oh, let me check. I didn't see the option for the fingerprint in the browser settings. Thanks.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by drakegao** [comment]
Thanks. I figured it out.  Very nice browser, thanks for the hard work.

2024年8月10日(土) 18:41 woheller69 ***@***.***>:
