### ISSUE TITLE
Bookmarks: directory return to the previous menu

### ISSUE THREAD

**Issue by Pantyhose-X** [woheller69/browser#6]
Bookmarks directory return to the previous menu.
People who have a lot of Bookmarks are very useful.

**Describe the solution you'd like**

- Open the site in the Bookmarks directory, click the back button to return to the bookmarks directory.

**Additional context**

https://user-images.githubusercontent.com/42504385/148888901-46bfb31e-988a-41d2-8105-a0a14cd6de18.mp4

**Comment by woheller69** [comment]
I don't see what this has to do with my browser

**Comment by Pantyhose-X** [comment]
> I don't see what this has to do with my browser

This is a Feature request
