### ISSUE TITLE
support: script Extensions search engine

### ISSUE THREAD

**Issue by Pantyhose-X** [woheller69/browser#7]
### script
https://openuserjs.org/
https://userscripts-mirror.org/index.html
https://www.userscript.zone/
https://gist.github.com/search?l=JavaScript&o=desc&q=%22%3D%3DUserScript%3D%3D%22&s=updated
### Extensions
https://chromewebstore.google.com/
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en-US
https://addons.mozilla.org/en-US/firefox/
https://addons.thunderbird.net/en-us/firefox/
https://addons.opera.com/en/
### search engine
Remove non-privacy search engine
It will give you country-specific results based on your country's ip, if you search for some non-popular sites in other countries, you won't find results, you chose other Regions in the search engine and he will still give you specific results based on the ip location.

#### non-privacy search engine
Yahoo
Bing
DuckDuckGo

#### privacy search engine
search.brave.com
eu.startpage.com
us.startpage.com
Yandex
qwant.com
Google #Gives specific results based on IP address, not very serious

**Comment by woheller69** [comment]
you can select your favourite seach engine, where is the issue?
